import Foundation

/// Phase 44 Plan 07: German dictation sentences drawn from this project's
/// own frozen corpus snapshot, for `PosTagger.measureAgreement`'s German
/// probe (`PosTaggerProbeTests`).
///
/// **Provenance (44-CORPUS-AUDIT.md's qwen-era subset — the model actually
/// in production per that audit):** every `.steps.post_rules.text` value
/// from every record with `lang == "de"` across the 9 qwen-era snapshot
/// files (`cleanup-2026-07-03.jsonl` through `cleanup-2026-07-12.jsonl`,
/// `.planning/phases/44-cleanup-fidelity-guard/corpus-snapshot/`) — 129
/// German records — was split into sentences on `.`/`!`/`?` followed by an
/// uppercase letter or digit, then deduplicated case-insensitively. That
/// yielded 300 unique sentences; **this fixture takes the first 200 in
/// original corpus order** (the plan's instructed cap). These are REAL
/// dictated German from this user, verbatim after the rules-cleanup
/// pipeline stage (before the LLM ever sees them) — not textbook German,
/// not hand-written test sentences. Includes ASR mishearings
/// (`"Testikdate"`, `"Monter"`), code-switched tech vocabulary (`"GSD"`,
/// `"AI Cleanup Mode"`), and a few short meta/test utterances
/// (`"hallo welt"`, `"phase251-lang-probe-…"`) exactly as they occur in the
/// corpus — RESEARCH's Pitfall 4 is specifically about NLTagger's accuracy
/// on THIS text distribution, so no cleanup or curation was applied beyond
/// the split/dedupe/cap described above.
public enum GermanPosProbeFixtures {
    /// 200 sentences (300 unique were available; capped per plan
    /// instruction — the true count and provenance are documented above and
    /// in `44-NLTAGGER-PROBE.md`).
    public static let sentences: [String] = [
        "Nun ja, jetzt folgen einige Testsätze und Testikdate, die du inhaltlich ignorieren kannst, aber natürlich solltest du Aufsatz, Struktur, Grammatik und so weiter achten.",
        "Ich halte hier die Hotkey Kombination gedrückt und werde Monter und fröhlich weiter diktieren.",
        "In der Vergangenheit war es ja auch so, dass es manchmal mit Deutsch und Englisch gleichen Diktat ein bisschen Mühe hatte.",
        "Darum werde ich jetzt auch immer wieder Anglizismen verwenden, zum Beispiel mit dieser Hotkey-Kombination, aber dann auch GSD, das ich ja nutze mit Claude Code zusammen für AI Assisted Coding und dann geht es eben weiter auf Deutsch.",
        "Das heisst, wenn wir nicht Busse tun dann werden keine busse für uns fahren und jetzt folgt auch ein abschnitt mit gebrochenem deutsch der sollte halt auch mit diesem AI Cleanup Mode bereinigt werden.",
        "Gestern habe dieser Chef angerufen und habe gesagt, fühle nicht gut und habe krank gemeldet.",
        "Chef hat gesagt, okay und nur ich nicht arbeite.",
        "Wie würdest du mein GSD?",
        "Und Hook Setup, vielleicht allfällige weitere Spezialkonfigurationen einer Person beschreiben, die mich nach meinen Erfahrungen mit GSD und Coding Agents fragt.",
        "Was sind hier vielleicht spezielle Dinge, die man als Tipps und Tricks hervorheben kann?",
        "hallo welt das ist ein test",
        "auf der anderen seite",
        "Ich habe einen 100",
        "phase251-lang-probe-B5B4F66E",
        "hallo welt",
        "phase251-lang-probe-B2BD6C25",
        "Sogar wenn ich leise auf Deutsch spreche, soll das eigentlich funktionieren.",
        "Dasselbe natürlich dann auch wieder mit dem AI Cleanup Mode, den ich jetzt aktiviert habe.",
        "Gib mir noch ein paar Hashtags.",
        "Die Marke ist unbekannt und ich würde sagen, wir beginnen mal mit 140 Franken.",
        "Auch hier muss die Ware in Zürich-Öhrlich-Kon abgeholt werden.",
        "dann beginnen wir mal mit 160 franken zu den massen des tisches habe ich aktuell keine angaben aber wenn die sitzhöhe 42 cm ist dann dürfte das tischlein 65 cm sein ungefähr.",
        "Das heisst die Höhe, breite Tiefe weiss ich nicht.",
        "Zur Gesamthöhe der Stühle habe ich ebenfalls keine Angaben.",
        "Und ich spreche nun gebrochene Deutsch.",
        "Heute habe Chef angerufen und gesagt: \"Fühle nicht gut.",
        "Bin krank, kann nicht komme, arbeite.\" Chef hat gesagt: \"Okay.\"",
        "Ich frage mich, wie das mit Schweizerdeutsch aussieht, denn das rede ich jetzt gerade.",
        "Und zwar, um ganz genau zu sein, Zürich-Deutsch.",
        "Das ist jetzt zwar nicht der Hauptanwendungsfall von der App, die wir hier testen, dem Dicticus, aber das sollte ja trotzdem irgendwie funktionieren.",
        "Und auch auf Deutsch kann ich mich natürlich auf eine sehr gehobene und gepflegte Art und Weise artikulieren, sodass dies grammatikalisch, aber auch stilistisch mehr als nur korrekt ist.",
        "Das Ganze geht natürlich auch auf Deutsch.",
        "Da kann ich einen ganzen und vor allen Dingen auch grammatikalisch runden Satz hervorbringen.",
        "Ich habe nämlich morgen ein Meeting um 10.30 Uhr.",
        "Ach nein, das ist um 11 Uhr.",
        "Ich habe morgen zudem um 14 Uhr ein Meeting.",
        "Nein, es ist um 15 Uhr.",
        "Ich habe um 15 Uhr ein Meeting.",
        "Ich möchte es nochmals auf Deutsch versuchen, denn ich glaube übermorgen habe ich ein Meeting um 9 Uhr.",
        "Also da die Self-Correction scheint nun besser zu funktionieren, auch wenn der eher Cleanup-Mode die Interpunktion, zumindest im Deutschen, nicht immer richtig hat.",
        "Also zu deiner ersten Frage: Ich würde Taskly als ernsthaften Kandidaten behandeln.",
        "Und zwar geht es für mich darum, zu eruieren, welche weiteren Optionen, nebst NoxWork, das nun offiziell bewilligt wurde, noch weiterverfolgt werden könnten und inskünftig auch neben NoxWork angeboten werden könnten.",
        "Beides, das heisst Taskly und WhatsApp API via Schweizer Business Solution Provider, müssen erst noch neue und separate PSDV Verfahren dort laufen.",
        "Doch wissen wir nun aufgrund der bisherigen Abklärungen worauf es ankommt.",
        "Vergleiche aber auch mit dem kantonalen VDG.",
        "Du solltest nämlich den IT-Security-Beurteilungstext in einem anderen Chat in diesem Projekt finden.",
        "Ehrlich gesagt weiss ich nicht, welche BSP-Anbieter auf dem Schweizer Markt tätig sind.",
        "Da möchte ich, dass du erst einmal eine Anbieterrecherche machst, einen Anbietervergleich und dann selbstständig zwei gut dokumentierte und vielversprechende in Frage kommende Anbieter auswählst und diese dann quasi als Grundlage nimmst für den Vergleich mit NoxWork und Taskly.",
        "Also auf der Organisationsseite würde ich sagen, dass es eine gemeinsame Inbox geben sollte und dass, selbst wenn es einzelne Mitarbeiterlogins geben sollte, dass man sich da einloggen kann und alles sieht.",
        "Also nichts sollte persönlich an einen Mitarbeiter gebunden sein, nur schon wegen Stellvertretung etc.",
        "Man sollte da so einen Posteingang bedienen können, vielleicht gibt es auch Triagemöglichkeiten zu einzelnen Mitarbeitern, ob diese dann als Mitarbeiter ausgewiesen werden gegenüber dem Kunden, ist das andere, das es zu prüfen gibt, muss wahrscheinlich nicht Vielleicht gibt es auch unterschiedliche Rollen, vielleicht so eine Adminrolle.",
        "Auch Wesenheitslogiken, automatische Benachrichtungen könnten schon Features sein, die eher für oder dann eben auch gegen ein Produkt sprechen.",
        "Die grundsätzliche Kritik bei Noxwork mag zwar sicher sein, aber die App hat praktisch niemand installiert.",
        "Zudem kostet sie einmalig 5 Franken.",
        "Das ist zwar nicht grundsätzlich viel, aber gerade für unsere Zielgruppen kann das natürlich ein Killerkriterium sein.",
        "Hier könnte man sich natürlich auch überlegen, ob wir das als Unternehmen zumindest das gewissen Zielgruppen bezahlen würden.",
        "Das wäre ja schlussendlich immer noch günstiger, als wenn wir beginnen würden, unseren Klienten selbst auch Lizenzen auszustellen.",
        "Also es sollte möglichst kostenlos sein.",
        "Ich finde es ist zumutbar, dass man da halt für die Behördenkommunikation eine separate App herunterlädt.",
        "Aber dann sollte es einfach zu bedienen sein und über die normalen Messenger-Möglichkeiten verfügen, die man heutzutage erwartet.",
        "Das können also sein, Bilder, Dateien anzuhängen, vielleicht auch eine Sprachnotiz, vielleicht auch eine Anruffunktion.",
        "Ja.",
        "Ich will hier wirklich eine ausführliche Recherche haben.",
        "Und falls du der Meinung bist, dass ich hierfür die Funktion Deep Research aktivieren sollte, dann gib Bescheid, bevor du loslegst.",
        "Dann werde ich diese dann noch aktivieren.",
        "Mir fällt nun noch ein, dass man vielleicht auch die Variante SMS mit einbeziehen sollte.",
        "Gerade weil jetzt auch zwischen iPhone und Android Geräten RCS ermöglicht ist.",
        "Hier hätte ich gerne eine Einschätzung, wie das grundsätzlich aussieht, wie sicher ist das und wie einfach ist das auch aus Organisationssicht.",
        "Die Idee ist ja nicht, dass man da jeweils vom Handy ausschreiben muss.",
        "Hier braucht es wahrscheinlich auch so eine BSP-Lösung.",
        "Eine vergleichbare Art und Weise.",
        "Damit man das vom Laptop aus bedienen kann.",
        "Also schau dir mal das erste Bild an, das geht ja so gar nicht auf, designtechnisch.",
        "Das ist viel zu nah aufeinander.",
        "Ich finde, du kannst oben ein bisschen weniger Buffer einplanen. unten links kannst du \"Design by Timo\" weglassen und vielleicht packst du den Sprachentoggle ebenfalls nach oben rechts und so haben wir unten dann vielleicht ein bisschen mehr Platz.",
        "Das zweite Bild finde ich in Ordnung.",
        "Der Default-Stundenersatz sollte hier 60 Franken pro Stunde betragen.",
        "Beim Bild 3 sollte das Stop-Symbol bei Meeting-Stoppeln so gross sein wie die Schrift selbst.",
        "Und hier gefällt es mir designtechnisch nicht ganz.",
        "Also die Zeit in weiss und gross finde ich okay.",
        "Der kleinere Schriftzug für den Geldbetrag finde ich okay.",
        "Die Farbe muss irgendwie angepasst werden.",
        "Das passt mir nicht so ganz.",
        "Beim vierten Bild sollten die Zeitangabe sowie die Geldangabe grösser sein.",
        "Da haben wir schon Platz dafür.",
        "Das sind schon fast wieder zu klein.",
        "Das fünfte Bild geht für mich in Ordnung.",
        "Hier fährt mir nur gerade auf, dass das ein Admin-Setting sein sollte, dass man hier Verlauf löschen kann.",
        "Und die Exportfunktion verstecken wir wohl für den Anfang besser auch.",
        "Mach nochmal so einen angepassten Vorschlag.",
        "Mockup.",
        "Also das Vergleichsdokument, sprich das Deliverable, sollte in einem HTML-Format sein.",
        "Und was mir extrem wichtig ist, ist, dass du alle Quellen, die du schlussendlich zitierst und auf die dich berufst, klar zitierst und referenzierst nach wissenschaftlicher Art und Weise direkt im Fliesstext.",
        "Also jeder Abschnitt sollte klar belegt sein, woher du diese Informationen und Aussagen hast.",
        "Du kannst natürlich dafür mit Fussnoten arbeiten.",
        "Das geht für mich in Ordnung.",
        "Falls es dir technisch möglich ist, und weil wir ja dann mit diesem HTML-Format arbeiten, wenn es bei diesen Quellen und Webseiten, die du konsultierst und zitierst, Veranschaulichungsbeispiele, Screenshots, Apps, Screenshots gibt, dann möchte ich, dass du diese kopierst und in diesen HTML-Bericht und Vergleich einfüGSD.",
        "Und bei SMS bzw.",
        "RCS, das kann wohl schon sein, dass das dann schlechter abschneiden wird.",
        "Trotzdem möchte ich es gründlich analysiert und verglichen haben.",
        "Beachte bei all dem die Schweizer Rechtsprechung, sowohl die kantonale Datenschutzvorgaben, wie auch die ID-Security-Beurteilung im Rahmen dieses Projektes.",
        "Also Standort Schweiz.",
        "Schweiz wird bei den Servern natürlich bevorzugt.",
        "Europa oder EU dürfte wohl noch knapp in Ordnung gehen.",
        "Alles ausserhalb der faktischen Ausschlusskriterium.",
        "Zu guter Letzt habe ich noch einen Zusatzauftrag für dich.",
        "Und zwar möchte ich, dass du recherchierst, ob es vergleichbare Open Source Messenger gibt, die zu unseren Anforderungen und Anwendungsfällen passen würden, die die man bei uns in der Stadt auf den eigenen Servern hosten und anbieten könnte.",
        "Hier hätte ich gerne einen grundsätzlichen Überblick, auch in Punkte Funktionen, Möglichkeiten und auch hinsichtlich der Machbarkeit.",
        "Wie einfach ist das, einen eigenen Messenger zu hosten? anzubieten, zu unterhalten etc.",
        "Dann eben nicht nur für interne Kommunikation, sondern vor allem für die Kommunikation nach aussen.",
        "Dann müsste es ja vielleicht gar nicht mehr zwangsläufig eine eigene Smartphone-App sein, sondern könnte vielleicht auch eine Web-App sein, die geräteagnostisch funktioniert.",
        "Ja, ich finde, wir können mit diesem Design weiterverfahren.",
        "Bei Task Chat möchte ich nachhaken, weil in meiner Vorstellung wäre das ein Self-Hosting auf den städtischen Servern oder auf der städtischen Infrastruktur und für mich Hostingbetreiber oder insgesamt Betreiber dieser Lösung wäre die ZID, also die zentrale IT der Stadt Aarheim.",
        "Und wenn TaskChat prinzipiell von Funktionen her in Frage kommen würde, dann möchte ich dich bitten, hierzu separat noch einmal zu recherchieren und auch zu skizzieren, wie ein Self-Hosting ausschauen könnte, was das bedeutet in puncto Infrastruktur, Wartungsaufwand, vielleicht auch Eigenleistung bezüglich End-to-End-Verschlüsselung oder auch für die Klientenseite.",
        "Und wenn wir das selbst hosten, ob dann der Standort USA von diesem Unternehmen überhaupt noch eine Rolle spielt.",
        "Während du wartest, möchte ich noch darauf hinweisen, wir haben diese Admin-Funktion versteckt.",
        "Indem wo sagen wir, wir wollen da lange drauf drücken.",
        "Und da jetzt oben links und oben rechts bereits durch Symbole besetzt sind, müsste das entweder unten links oder unter rechts sein.",
        "Also mir fällt im Impressum auf, dass da meine E-Mail-Adresse steht, die will ich dann gestrichen haben, weil wir haben ja dieses Kontaktformular und ich möchte so auch Spam vermeiden.",
        "Der LinkedIn-Link funktioniert nun.",
        "Vielen Dank dafür.",
        "Bezüglich dem Kontaktformular beim Freitextfeld müsste die maximale Zeichenlänge angegeben werden und es bräuchte einen Counter, der anzeigt, wie viele Zeichen ich bereits verbraucht habe.",
        "Zudem frage ich mich, ob das Kontaktformular bzw. das freie Textfeld im Rich Text Format ist.",
        "Ich kann da zwar Absätze einfügen, das scheint auch so funktionieren und als E-Mail anzukommen.",
        "Und es geht mir jetzt nicht darum, dass man da hier einen Texteditor einfügt, aber dass zum Beispiel Links auch tatsächlich als solche erkannt werden.",
        "Oder E-Mail-Adressen.",
        "Also mich nimmt hier mal Wunder, was du hier brauchst oder was du einstellst, weil das sieht für mich nicht nach 90% Dimming aus.",
        "Also recherchiere mal, was es für Mechanismen gibt, wie diesen Touchscreen von Pi oder das Pi selbst.",
        "Und dann, ja, schau mal, ob du das noch dunkler kriegst, weil es ist nicht optisch, der Unterschied ist nicht 90%.",
        "Also Übersetzung sowie Anonymisierung und Pseudonymisierung würde ich definitiv auch als Standardservice mit aufnehmen.",
        "Dann ist ebenfalls anzufügen, dass noch Handlungsbedarf in puncto MüraX Schulungsmaterial und Unterlagen besteht.",
        "Die Sharepoint-Seite zu MüraX KI-Portal ist noch ausbaufähig.",
        "Zudem ist anzustreben, dass alle Informationen rund um MüraX zentral an einem Ort zu finden sind und nicht verteilt sind.",
        "Hast du genügend Informationen zur Würdigung der bisherigen Leistung?",
        "Das sollte auch in den Medien vorgekommen sein.",
        "Das finde ich ganz okay.",
        "Aber ich glaube, es geht darum, der ZID aufzuzeigen, dass es weitere Leistung benötigt und dass wir uns nicht ausruhen können.",
        "Denn die Bedürfnisse sind da und je länger wir zuwarten und, sagen wir mal, MüraX einem schwachen Zustand lassen, desto eher ist es auch ein Sicherheitsrisiko, dass halt viele Leute bzw.",
        "Mitarbeiter dann externe KI-Tools verwenden.",
        "Ein konkreter Vorschlag, wie man das erreichen könnte, denn all dies benötigt natürlich Ressourcen, das ist mir schon bewusst, wäre beispielsweise, dass gemeinsam, also ZID und Dienstabteilungen, neue Features priorisieren und man dann auch schaut, im punkt ressourcen pooling vielleicht können personelle ressourcen nicht in weniger prozent der fälle aber auch finanzielle ressourcen gepult werden um eben für die ganze stadt etwas tolles und vor allem auch rechtzeitig zur verfügung stehendes zu erarbeiten",
        "Und natürlich sollte der offene Brief diplomatisch formuliert sein und trotzdem auch einen gewissen Unmut zum Ausdruck bringen und dass es so nicht weitergehen kann.",
        "Und ich glaube, hier wäre das stärkste Argument der Verweis auf die Digitalisierungsstrategien, wie man halt in diesem Bereich teilweise vielleicht nicht oder noch nicht konform ist.",
        "Du kannst das mal generell an die Uhrzeit richten.",
        "Ich mache mir dann noch konkret Gedanken dazu, an wen das adressiert sein müsste oder wie man das dann tatsächlich in Umlauf bringt.",
        "Das gleiche dann auch mit den Absendern.",
        "Also das wäre dann einfach ein Konglomerat von verschiedenen Dienstabteilungen oder Vertretern von Dienstabteilungen, beispielsweise Digitalisierungsverantwortliche.",
        "Bezüglich Format gehe ich mit dir ein, das sollte so passen.",
        "Und ja, pack das mal in ein Word-Dokument.",
        "Also in der aktuellen Ausprägung ergibt der Sprachentoggle im Admin Panel keinen Sinn, weil der ist eins zu eins an den Sprachentoggle auf dem Startbildschirm geknüpft und da das ja praktisch nur für mich ist, geht sowohl Deutsch als auch Englisch in Ordnung.",
        "Also streiche diesen Sprachentoggle komplett aus dem Admin Panel.",
        "Die Implementierung von den Auf- und Abwärtsknöpfen unten links finde ich nicht gut.",
        "Ich möchte, dass du diese Auf- und Abwärtsknöpfe rechts von der Tabelle platzierst.",
        "Also macht die Tabelle insgesamt ein bisschen schmaler. und dann ist der Aufwärtsknopf oben bündig und der Abwärtsknopf ist unten bündig.",
        "Und dann kann man so hin und her scrollen.",
        "Und auch die Scrollbar sollte ein bisschen besser visuell aufbereitet sein, sodass man sieht, ob man jetzt da noch, muss man nach oben oder nach unten.",
        "Die drei neuen Seiten sind im Grundsatz okay.",
        "Die sollten auf jeden Fall auch nicht spezifischer oder detaillierter sein, gerade was den Inhalt betrifft, weil das ja auch sich verändern kann oder je nach Kunde ein bisschen anders gestaltet sein kann.",
        "Was mir sofort auffällt, ist der Gebrauch der vielen Gedankenstriche.",
        "Das will ich überhaupt nicht und gefällt mir auch nicht, das muss geändert werden.",
        "Und dann habe ich mich noch gefragt, weil das ist tatsächlich etwas, was ich begonnen habe bei meinem aktuellen Arbeitgeber, und zwar biete ich ein Fitness-Coaching an.",
        "Das sind vier 60-Minuten-Einheiten, in denen verschiedene Aspekte rund um Fitness, die für den Alltag relevant sind, besprochen werden, inklusive Transferaufgaben etc.",
        "Würdest du das auch aufführen?",
        "In welcher Form?",
        "Wie würde sich das preislich einordnen?",
        "Hier brauchst du noch nichts umzusetzen, aber ich möchte gerne darüber sprechen.",
        "Der Verlauf sieht nun ok aus mit diesen Auf- und Abwärts-Buttons, jedoch kann man die Zurückschaltfläche komplett streichen, denn die ist redundant mit dem X-Button oben rechts.",
        "Und während ich das so geprüft habe, habe ich mich gefragt, was ist denn eigentlich der Sinn dieses Verlaufs und ob es nicht viel nutzerfreundlicher wäre, wenn wir eine Auswertungsseite machen würden, wo wir zeigen, Was ist beispielsweise die durchschnittliche Teilnehmerzahl, durchschnittliche Meetingdauer?",
        "Sind die Leute zufrieden?",
        "In so einem Rolling Average?",
        "Ja, mache hier mal ein paar konkrete Vorschläge als Mockup mit verschiedenen Indikatoren und Metriken, die man... aus den Daten, die wir jetzt erfassen, herauslesen könnte und in einem Analyse-Dashboard-Screen darstellen könnte, anstelle des Verlaufs.",
        "Der Verlauf könnte ja tatsächlich ins Admin-Panel wandern.",
        "Also deinen Dashboard Vorschlag finde ich gut.",
        "Mit dem können wir mal so verfahren.",
        "Du kannst jetzt aber die Phase 1 erst abschliessen und dann in der geeigneten oder vorgesehenen Phase auf diesen Dashboard-Vorschlag zurückkommen.",
        "Wir lassen das vorerst mal in einer Art Backlog und veröffentlichen es noch nicht.",
        "Also ich würde sagen, wir nehmen Mittagessen und dann würde ich noch recherchieren, was ein Skitag kostet.",
        "Ein Skiticket pro Tag.",
        "Ich glaube, das bewegt sich so um die durchschnittlich 100 Franken.",
        "Das könnte dann erst grössere Brocken sein.",
        "Das können wahrscheinlich viele einordnen.",
        "Aber recherchiere das kurz.",
        "Also, um ganz ehrlich zu sein, die Visualisierung gefällt mir noch nicht so ganz.",
        "Die wirkt noch ein wenig plump.",
        "Da kann durchaus ein bisschen mehr Mühe und Liebe hineinfliessen.",
        "Dann zu deiner früheren Aussage, dass wir hier auf einem Entwurf basieren.",
        "Das mag sein und soll eigentlich auch so sein, weil das, was du im Internet findest, ist nicht die aktuellste Version.",
        "Ob schon natürlich der Entwurf nicht der offiziellen und publizierten Version entspricht, so widerspiegelt es die aktuelle Doktrin.",
        "Das müssen wir aber so nicht explizit ausweisen.",
        "Es geht vor allem einfach darum, dass aktualisierte Begriffe, denn der Entwurf ist teilweise leicht anders formuliert, dass die sich in unserem Webservice widerspiegeln.",
        "Ich habe mich gefragt, ob wir an irgendeiner Stelle Quizfragen oder Lernkontrollen eingebaut haben.",
        "Kommt das erst später?",
        "Ist es dann insgesamt?",
        "Oder würden wir das pro Kapitel einbauen wollen?",
        "Also vielleicht nicht nur dieses...",
        "Schlusszitat oder wie man dem auch immer sagen will, was du eingefügt hast, ganz am Ende des Kapitels, sondern vielleicht auch zwei bis drei Kontrollfragen, um das Ganze vielleicht noch ein bisschen zu animieren und interaktiver zu gestalten.",
        "Was meinst du?",
        "Okay, das passt für mich so.",
        "Wie geht es nun weiter?",
        "Und was ist mit Single- oder Multiple-Choice-Fragen?",
        "Und vielleicht finden wir ja auch noch eine etwas kreativere Art Wissen abzufragen, indem wir beispielsweise eine Visualisierung nehmen."
    ]
}
